version: '3'

services:
    eventservice:
        build: "./EventService"
        image: 'davi7816/testeventservice:<TAG>'
    ratingservice:
        build: "./RatingService"
        image: 'davi7816/testratingservice:<TAG>'
    creationservice:
        build: "./CreationService"
        image: 'davi7816/testcreationservice:<TAG>'
    driverservice:
        build: "./DriverService"
        image: 'davi7816/testdriverservice:<TAG>'
    loggerservice:
        build: "./LoggerService"
        image: 'davi7816/testloggerservice:<TAG>'
    locationservice:
        build: "./LocationService"
        image: 'davi7816/testlocationservice:<TAG>'
    notificationservice:
        build: "./NotificationService"
        image: 'davi7816/testnotificationservice:<TAG>'
    webapplication:
        build: "./WebApp"
        image: 'davi7816/testwebapp:<TAG>'
    rmiconnector:
        build: "./RMIConnector"
        image: 'davi7816/testrmiconnector:<TAG>'